### ISSUE TITLE
Error(3024) Posted at 64% While running Engine Update through Vortex Tool

### ISSUE THREAD

**Issue by AnsionEsre** [ShikyoKira/Project-New-Reign---Nemesis-Main#122]
Initializing engine update

ERROR(3024): Duplicated header has been detected in "animationdatasinglefile.txt". Please contact the template creator
Template: behavior templates\__folder_managed_by_vortex
Project: <2>
Header: <3>

Failed to update engine
[UpdateLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/3976182/UpdateLog.txt)

**Comment by ShikyoKira** [comment]
Vortex messes with the folders and animationdatasinglefile.txt. Try using MO2 instead for now. I will contact Vortex developers in near future regarding this matter

**Comment by AnsionEsre** [comment]
So it is a problem with using Vortex? 
I'm sorry but I guess I will not be using your tool then. I really did enjoy it, but I do not enjoy using MO2 or the bias it has in the community as the one tool.
I'll follow up in time to see if this has been corrected. Thank you for responding.

**Comment by Shavv** [comment]
Im having the same problem, and all my 2000+ mods are managed by Vortex. Going over would be such a pity as I would have to restart all over again.

**Comment by chibi4** [comment]
I'm using v0.83bSE and got the same error at first. The program tries to interpret these __folder_managed_by_vortex files. It's a text file that reads "This directory was created by Vortex deployment and will be removed during purging if it's empty". Since they don't contain any meaningful information for Nemesis, an error occurs. 
By deleting the "__folder_managed_by_vortex" file in Nemesis_Engine, the update continues until a different error - caused by another __folder_managed_by_vortex file in another sub-directory. Since I didn't have the patience to continue deleting each __folder_managed_by_vortex file in every folder, I simply manually copied the Nemesis_Engine folder into Skyrim's data directory. Now it updates as expected and the Engine runs fine as well.

It would be very helpful if your Nemesis Engine could be programmed to ignore these files. The "animationdatasinglefile.txt" file and any other files are not modified by Vortex.

**Comment by Shavv** [comment]
> I'm using v0.83bSE and got the same error at first. The program tries to interpret these __folder_managed_by_vortex files. It's a text file that reads "This directory was created by Vortex deployment and will be removed during purging if it's empty". Since they don't contain any meaningful information for Nemesis, an error occurs.
> By deleting the "__folder_managed_by_vortex" file in Nemesis_Engine, the update continues until a different error - caused by another __folder_managed_by_vortex file in another sub-directory. Since I didn't have the patience to continue deleting each __folder_managed_by_vortex file in every folder, I simply manually copied the Nemesis_Engine folder into Skyrim's data directory. Now it updates as expected and the Engine runs fine as well.
> 
> It would be very helpful if your Nemesis Engine could be programmed to ignore these files. The "animationdatasinglefile.txt" file and any other files are not modified by Vortex.

This is not do-able if you have mods that depend on it. For example: the dark souls animation mod that requires Nemesis to patch it out without being in the list as a standard. Some mods may appear later in the list and if you install this manually, this is not an option. This only works if you install nemesis manually and have no mod that isn't in the list, or have mods that are as a standard in the list for a patch. 

So i don't recommend this.

**Comment by chibi4** [comment]
I'm not sure if I completely understood you, but I tried with XPMSSE, Engarde and [Combat Behavior Compulsion (SGC - SkySA)](https://www.nexusmods.com/skyrimspecialedition/mods/31390) now. Installing the last one normally leads to errors again, but at least the option to manually copy the mod's Nemesis folder over exists. That adds a skysa folder under Data\Nemesis_Engine\mod so it's not unmanagable. 

Then Nemesis runs. It's certainly not a nice long term solution but at least it works. (Didn't test ingame yet, but assume it works.)

**Comment by ShikyoKira** [comment]
Fixed in v0.83c

**Comment by clootas** [comment]
I have this exact same problem using Nemesis on MO2, and I'm on the latest version of Nemesis. Any pointers?

Modlist: https://modwat.ch/u/Stootas/plugins

**Comment by shmediaproductions** [comment]
^ if you're using MO2 and getting this exact error message then it clearly means you used to use vortex. you must have installed this mod with vortex and then switched to MO2. you would need to go into the Nemesis_engine folder and search/find all files called _folder_managed_by_vortex and delete them. but i don't think you need to do this anymore in the first place? if you're actually using the latest version of nemesis then you shouldn't get this error at all, because it has an exception for these files and doesn't interpret them as templates. i have nemesis installed through vortex and my folders are full of these files and I don't get any errors running nemesis. I would suggest you uninstall Nemesis completely (delete the nemesis_engine folder) and reinstall the latest version through whichever mod manager you're currently using.

**Comment by VulcanTourist** [comment]
Why was this ticket marked as fixed in January 2020?  Here it is October 2020, and I'm getting that exact same behavior and error from Nemesis, merely because my choice of mod manager happens to be Vortex?
`Initializing engine update

ERROR(3024): Duplicated header has been detected in "animationdatasinglefile.txt". Please contact the template creator
Template: behavior templates\anim_object.txt.vortex_backup
Project: <2>
Header: <3>

Failed to update engine`

**Comment by mangoman2000** [comment]
Initializing engine update

ERROR(3024): Duplicated header has been detected in "animationdatasinglefile.txt". Please contact the template creator
Template: behavior templates\__folder_managed_by_vortex
Project: <2>
Header: <3>

Failed to update engine

Skyrim SE with SKSE64 and SKYUI and nemesis. Trying this after about 10 months, issue is still there.

Why not just put in a disclaimer and handle this error. Hasnt it been too long in the works?

**Comment by RonYuma** [comment]
just started to have this problem, first time installing nemesis 

ERROR(3020): Invalid format for "animationdatasinglefile.txt" in InfoData section has been detected

I never used vortex before, always mo2, has this been fixed yet

**Comment by skftwins** [comment]
I was having this issue while using Vortex and tried a few things but I found a method that worked for me
Courtesy of RedditUser AMGarkin

1 month ago
When Vortex detects existing file in destination folder (which wasn't added by Vortex), it will make backup copy like that.

To solve this problem simply delete file <game>\Data\Nemesis_Engine\behavior templates\behavior templates\anim_object.txt.vortex_backup or move this file somewhere else. You should do the same for all *.vortex_backup files inside of Nemesis_Engine folder.
