### ISSUE TITLE
ERROR(1166): BUG FOUND!! Report to Nemesis' author immediately

### ISSUE THREAD

**Issue by ElvenScoundrel** [ShikyoKira/Project-New-Reign---Nemesis-Main#239]
I updated both CGO and Nemesis and not only does that make the game crash upon starting a new game or loading a save, I also got this error.

**Comment by ElvenScoundrel** [comment]
[CriticalLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4566935/CriticalLog.txt)

**Comment by IdaeroAce** [comment]
I’m having that problem yesterday o.o
Are you only use CGO?
I install CGO + AGO + TUDM. but idk what happen, i give up tudm and it works. This TUDM v4 is from (DMC) TUDM gdrive link on Nexus
(the game still crashing though because later i realized I replace XPMSE skeleton)

**Comment by ElvenScoundrel** [comment]
I'm using CGO+AGO and TK Dodge. That's about it on mods that alter animations.

**Comment by ShikyoKira** [comment]
send me your patchlog.txt

**Comment by ElvenScoundrel** [comment]
[PatchLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4570946/PatchLog.txt)

**Comment by 9JANOOB** [comment]
this error pops out everytime i click on the ultimate combat/tk dodge check mark. I've tested different variations with same result. tk dodge alone. ultimate combat alone, and both. i even uninstalled CGO and AGO with 360 Movement Behavior just to be sure they are not the cause and tried different variations with them. I'm not sure what exactly causes this error to pop up but i'm confident it has to do with tk ultimate combat/tk dodge

**Comment by ShikyoKira** [comment]
Thanks for the update. It should be fixed in the latest version. I have regenerated the patch for UC/TK

**Comment by peter-nt** [comment]
To anyone who still run into this issue and using MO2 - make sure that TK Dodge is below Nemesis, but above Nemesis output.
Meaning the TK Doge priority should be:  Nemesis < TK Dodge Priority > Nemesis output

**Comment by navarromluisdavid** [comment]
I'm having the same problem right now and I don't have TK Dodge installed. Everything was working fine until I installed a new animation package and this bug came up. But uninstalling this package did not fix the problem. Oh and the variable name is <1>, a lot of information, I know

**Comment by ItsChevnotJeff** [comment]
> To anyone who still run into this issue and using MO2 - make sure that TK Dodge is below Nemesis, but above Nemesis output. Meaning the TK Doge priority should be: Nemesis < TK Dodge Priority > Nemesis output

Doesn't work
